version: '3'

services:
  fastapi:
    build:
      context: ./dockerfiles
      dockerfile: fastapi.dockerfile
    ports:
      - "5500:5500"
    volumes:
      - ./src/expert-system:/app

  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./src/web-app:/var/www/html:delegated
    depends_on:
      - fastapi
      - php

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./src/web-app:/var/www/html:delegated

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src/web-app:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  npm:
    image: node:current-alpine
    volumes:
      - ./src/web-app:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
